# Combine the shards written by run.R into results/summary.csv and REPORT.md.
#   Rscript validation/calibration/summarise.R DIR_WITH_SHARDS [OUT_DIR]

args <- commandArgs(trailingOnly = TRUE)
shard_dir <- args[1]
out_dir <- if (length(args) > 1) args[2] else "validation/calibration/results"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

files <- sort(list.files(shard_dir, "^shard-[0-9]+\\.rds$", full.names = TRUE, recursive = TRUE))
if (!length(files)) stop("no shard files in ", shard_dir)
shards <- lapply(files, readRDS)
info <- attr(shards[[1]], "info")
if (length(files) != info$nshards) stop("found ", length(files), " of ", info$nshards, " shards")
cells <- names(shards[[1]])
raw <- stats::setNames(lapply(cells, function(cell) {
  m <- do.call(rbind, lapply(shards, `[[`, cell))
  m[order(m[, "rep"]), , drop = FALSE]
}), cells)
expected <- function(cell) if (startsWith(cell, "zc")) info$R_ZC else info$R_DBZ
for (cell in cells) {
  if (!identical(as.integer(raw[[cell]][, "rep"]), seq_len(expected(cell)))) {
    stop("cell ", cell, ": replications missing or duplicated")
  }
}
saveRDS(structure(raw, info = info), file.path(out_dir, "raw.rds"))

summarise_metric <- function(v) {
  R <- length(v)
  binary <- all(v %in% c(0, 1))
  se <- sd(v) / sqrt(R)
  ci <- if (binary) stats::binom.test(sum(v), R)$conf.int else pmin(pmax(mean(v) + c(-1, 1) * 1.96 * se, 0), 1)
  c(R = R, estimate = mean(v), mc_se = se, lower95 = ci[1], upper95 = ci[2])
}
summary <- do.call(rbind, lapply(cells, function(cell) {
  m <- raw[[cell]]
  metrics <- setdiff(colnames(m), "rep")
  do.call(rbind, lapply(metrics, function(metric) {
    data.frame(cell = cell, metric = metric, t(summarise_metric(m[, metric])))
  }))
}))
write.csv(summary, file.path(out_dir, "summary.csv"), row.names = FALSE)

fmt <- function(cell, metric) {
  r <- summary[summary$cell == cell & summary$metric == metric, ]
  sprintf("%.3f [%.3f, %.3f]", r$estimate, r$lower95, r$upper95)
}
table_md <- function(cells, metrics, labels) {
  head <- c(paste("| setting |", paste(labels, collapse = " | "), "|"),
            paste0("|---|", strrep("---|", length(metrics))))
  rows <- vapply(cells, function(cell) {
    paste("|", cell, "|", paste(vapply(metrics, fmt, "", cell = cell), collapse = " | "), "|")
  }, "")
  c(head, rows)
}
dbz <- grep("^dbz", cells, value = TRUE)
zc <- grep("^zc", cells, value = TRUE)
report <- c(
  "# Calibration study (generated by summarise.R)", "",
  sprintf("SILM %s; n = %d, p = %d; B = %d bootstrap samples; M = %d multiplier samples; %d (DBZ) and %d (ZC) response replications per setting; %d shards.",
          info$silm, info$N, info$P, info$B, info$M, info$R_DBZ, info$R_ZC, info$nshards),
  "Estimates with 95% Monte Carlo intervals (exact binomial for 0/1 outcomes). Nominal level 95% (coverage) and 5% (FWER).", "",
  "## boot.lasso.proj (robust standard errors, one fixed Toeplitz(0.5) design)", "",
  table_md(dbz, c("ind_cov", "ind_cov_S0", "joint_maxmin", "joint_abs", "fwer_wy", "power_wy"),
           c("indiv. coverage", "indiv. coverage S0", "joint (maxmin)", "joint (abs)", "WY FWER", "WY power")),
  "", "Asymptotic lasso.proj() on the same responses (robust, same divisor):", "",
  table_md(dbz, c("asym_ind_cov", "asym_ind_cov_S0", "asym_fwer_holm", "asym_power_holm"),
           c("indiv. coverage", "indiv. coverage S0", "Holm FWER", "Holm power")),
  "", "## Sim.CI / Step (one fixed Toeplitz(0.9) design, t(4) errors)", "",
  table_md(zc, c("joint_nst", "joint_st", "joint_nst_S0", "joint_nst_S0c", "fwer_step_nst", "power_step_nst"),
           c("joint NST [p]", "joint ST [p]", "joint NST S0", "joint NST S0^c", "Step FWER (NST)", "Step power (NST)")))
writeLines(report, file.path(out_dir, "REPORT.md"))
writeLines(info$session, file.path(out_dir, "session.txt"))
cat(report, sep = "\n")
